/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "LDSSecurityObject"
 * 	found in "efsod.asn1"
 */

#ifndef	_DataGroupNumber_H_
#define	_DataGroupNumber_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DataGroupNumber {
	DataGroupNumber_dataGroup1	= 1,
	DataGroupNumber_dataGroup2	= 2,
	DataGroupNumber_dataGroup3	= 3,
	DataGroupNumber_dataGroup4	= 4,
	DataGroupNumber_dataGroup5	= 5,
	DataGroupNumber_dataGroup6	= 6,
	DataGroupNumber_dataGroup7	= 7,
	DataGroupNumber_dataGroup8	= 8,
	DataGroupNumber_dataGroup9	= 9,
	DataGroupNumber_dataGroup10	= 10,
	DataGroupNumber_dataGroup11	= 11,
	DataGroupNumber_dataGroup12	= 12,
	DataGroupNumber_dataGroup13	= 13,
	DataGroupNumber_dataGroup14	= 14,
	DataGroupNumber_dataGroup15	= 15,
	DataGroupNumber_dataGroup16	= 16
} e_DataGroupNumber;

/* DataGroupNumber */
typedef long	 DataGroupNumber_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DataGroupNumber;
asn_struct_free_f DataGroupNumber_free;
asn_struct_print_f DataGroupNumber_print;
asn_constr_check_f DataGroupNumber_constraint;
ber_type_decoder_f DataGroupNumber_decode_ber;
der_type_encoder_f DataGroupNumber_encode_der;
xer_type_decoder_f DataGroupNumber_decode_xer;
xer_type_encoder_f DataGroupNumber_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _DataGroupNumber_H_ */
#include <asn_internal.h>
