/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "LDSSecurityObject"
 * 	found in "efsod.asn1"
 */

#ifndef	_DataGroupHash_H_
#define	_DataGroupHash_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DataGroupNumber.h"
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DataGroupHash */
typedef struct DataGroupHash {
	DataGroupNumber_t	 dataGroupNumber;
	OCTET_STRING_t	 dataGroupHashValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DataGroupHash_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DataGroupHash;

#ifdef __cplusplus
}
#endif

#endif	/* _DataGroupHash_H_ */
#include <asn_internal.h>
