/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "LDSSecurityObject"
 * 	found in "efsod.asn1"
 */

#ifndef	_LDSSecurityObject_H_
#define	_LDSSecurityObject_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LDSSecurityObjectVersion.h"
#include "DigestAlgorithmIdentifier.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct DataGroupHash;

/* LDSSecurityObject */
typedef struct LDSSecurityObject {
	LDSSecurityObjectVersion_t	 version;
	DigestAlgorithmIdentifier_t	 hashAlgorithm;
	struct dataGroupHashValues {
		A_SEQUENCE_OF(struct DataGroupHash) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} dataGroupHashValues;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LDSSecurityObject_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LDSSecurityObject;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "DataGroupHash.h"

#endif	/* _LDSSecurityObject_H_ */
#include <asn_internal.h>
