/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "LDSSecurityObject"
 * 	found in "efsod.asn1"
 */

#ifndef	_LDSSecurityObjectVersion_H_
#define	_LDSSecurityObjectVersion_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* LDSSecurityObjectVersion */
typedef long	 LDSSecurityObjectVersion_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LDSSecurityObjectVersion;
asn_struct_free_f LDSSecurityObjectVersion_free;
asn_struct_print_f LDSSecurityObjectVersion_print;
asn_constr_check_f LDSSecurityObjectVersion_constraint;
ber_type_decoder_f LDSSecurityObjectVersion_decode_ber;
der_type_encoder_f LDSSecurityObjectVersion_encode_der;
xer_type_decoder_f LDSSecurityObjectVersion_decode_xer;
xer_type_encoder_f LDSSecurityObjectVersion_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _LDSSecurityObjectVersion_H_ */
#include <asn_internal.h>
