name: Deploy

on:
  push:
    branches:
      - master

env:
  NODE_VERSION: 10

jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup npm registry
        env:
          NPM_TOKEN: ${{ secrets.DEPLOY_NPM_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" \
            > $HOME/.npmrc

      - name: Kyber
        run: |
          cd external/js/kyber
          npm ci
          npm version prerelease --preid=p`date +%y%m.%d%H.%M%S`
          ./publish.sh --tag dev

      - name: Cothority
        run: |
          cd external/js/cothority
          npm ci
          npm version prerelease --preid=p`date +%y%m.%d%H.%M%S`
          ./publish.sh --tag dev
