name: Full Test

on:
  schedule:
    - cron: "12 6 * * 1-5"

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: running tests
        run: go test -race ./...
