name: Full Test

on:
  schedule:
    - cron: "12 6 * * 1-5"

env:
  GO_VERSION: 1.15

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: running tests
        run: go list -f '{{.Dir}}' ./... | xargs -n1 go test -race
