name: Test

on:
  workflow_run:
    workflows: ["Lint and Build"]
    types:
      - completed

env:
  GO_VERSION: 1.15
  NODE_VERSION: 10
  JAVA_VERSION: 9.0.4

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: running tests
        run: |
          find . -name "*_test.go" | \
            xargs -n 1 dirname | sort | uniq | \
            xargs -n 1 go test -count=1 -race -short

  java:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - name: running tests
        run: make test_java

  js-kyber:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: test
        run: |
          cd external/js/kyber
          npm ci
          npm test

  js-cothority:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: test
        run: |
          make docker
          pushd external/js/kyber && npm ci && npm run link && popd
          cd external/js/cothority
          npm ci
          npm test
