name: Test

on:
  workflow_run:
    workflows: ["Lint and Build"]
    types:
      - completed

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - uses: actions/setup-python@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: running tests
        run: |
          git clone https://github.com/dedis/Coding
          ./Coding/bin/coveralls.sh

  java:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - uses: actions/setup-java@v1
        with:
          java-version: '9.0.4' # The JDK version to make available on the path.

      - name: running tests
        run: |
          make test_java

  js-kyber:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: test
        run: |
          cd external/js/kyber
          npm ci
          npm test

  js-cothority:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: test
        run: |
          make docker
          pushd external/js/kyber && npm ci && npm run link && popd
          cd external/js/cothority
          npm ci
          npm test
